FROM nvidia/cuda:8.0-cudnn5-devel
MAINTAINER Kai Arulkumaran <design@kaixhin.com>

RUN apt-get update && apt-get install -y \
  git \
  libopenblas-dev \
  libopencv-dev \
  python-dev \
  python-numpy \
  python-setuptools \
  wget

RUN cd /root && git clone --recursive --branch v0.9.3 --progress -v https://github.com/dmlc/mxnet.git && \
  cp make/config.mk config.mk && \
  sed -i 's/USE_BLAS = atlas/USE_BLAS = openblas/g' config.mk && \
  sed -i 's/USE_CUDA = 0/USE_CUDA = 1/g' config.mk && \
  sed -i 's/USE_CUDA_PATH = NONE/USE_CUDA_PATH = \/usr\/local\/cuda/g' config.mk && \
  sed -i 's/USE_CUDNN = 0/USE_CUDNN = 1/g' config.mk && \
  make -j"$(nproc)"

RUN cd /root/mxnet/python && python setup.py install

RUN echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y --force-yes r-base

CMD ln /dev/null /dev/raw1394

WORKDIR /root/mxnet